### ISSUE TITLE
Custom Section from Blob

### ISSUE THREAD

**Issue by bkotsopoulossc** [GoogleChromeLabs/wasmbin#6]
Hi @RReverser, I am trying to use the library to encode a custom section that has a name and some contents, and I want the contents to come from an encoded RawBlob, such that the actual binary contents (Vec<u8>) are prefixed by the LEB128. I'm a bit confused how to do this, any pointers?

**Comment by RReverser** [comment]
Hm, not sure I understand. Are you saying your binary contents already have leb128 and you don't want wasmbin to add one? Or, perhaps, can you show how you're doing it now and what is the expected result vs actual one? That will be a bit easier to discuss.

**Comment by bkotsopoulossc** [comment]
Sorry, I didn't explain that well at all. Here's what I am trying to do
```
        module
            .sections
            .push(Section::Custom(Blob::from(CustomSection::Other(
                RawCustomSection {
                    name: "some_section_name".to_string(),
                    data: some_u8_vec, // does not have leb128, but needs it
                },
            ))));
```

This is what I imagine I want to do, or something along these lines, but I'm not sure
```
        module
            .sections
            .push(Section::Custom(Blob::from(CustomSection::Other(
                RawCustomSection {
                    name: "some_section_name".to_string(),
                    data: Blob::from(some_u8_vec).encode_to_vec(), // Blob encoding handles leb128 for this binary data
                },
            ))));
```

**Comment by RReverser** [comment]
Sorry for not responding over the holidays. Yeah, what you're doing makes sense, although I can see how this might be a somewhat common usecase and perhaps we need some better support for custom types in custom sections... I'm not sure what it would look like though (`Box<dyn Wasmbin>`?).

**Comment by bkotsopoulossc** [comment]
> Sorry for not responding over the holidays. 
No worries at all, happy holidays

> for custom types in custom sections
In my case, just supporting the leb128 prefix for u8 Vecs used in custom sections would be sufficient. I imagine u8 Vecs covers a lot of custom sections anyways, even strings seem to use this convention

**Comment by bkotsopoulossc** [comment]
To be more specific, this is the custom section I was working on (`external_debug_info`): https://github.com/WebAssembly/tool-conventions/blob/08bacbed7d0daff49808370cd93b6a6f0c962d76/Debugging.md#external-dwarf

**Comment by RReverser** [comment]
FWIW I'd be open to adding this and any other custom sections as variants to the existing enum with known custom sections. But it would be nice to come up with some generic solution too...

**Comment by bkotsopoulossc** [comment]
It seems like we can achieve the generic solution like so:
```
use wasmbin::io::Encode;

  let data_vec = &mut Vec::new();
  contents_that_i_want_serialized.encode(data_vec).unwrap();

  module
      .sections
      .push(Section::Custom(Blob::from(CustomSection::Other(
          RawCustomSection {
              name: "my_section_name".to_string(),
              data: contents_that_i_want_serialized.to_vec(),
          },
      ))));
```

**Comment by RReverser** [comment]
I'm guessing this was resolved.
